### ISSUE TITLE
Publish at Maven Central

### ISSUE THREAD

**Issue by nichtich** [thunken/beacon#2]
And get a [nice badge](https://shields.io/).

**Comment by lucboruta** [comment]
Now that [JitPack](https://jitpack.io/#thunken/beacon) is available to get artifacts from Git repositories, I find Sonatype's process rather cumbersome.

I recommend using JitPack to include this lib as a dependency in other projects—I'll update the README accordingly today—but I'll try to look into Maven Central at some point.

**Comment by nichtich** [comment]
Ok, I'm not familiar what's best practice in the Java, just looked at [this comparison](http://www.modulecounts.com/). Coming from a library world I better trust repositories which archive explicitly deposited artifacts instead of relying on git repositories. Anyway, I'll try JitPack, it also has badges ;-)
