### ISSUE TITLE
Adjust to next draft of BEACON

### ISSUE THREAD

**Issue by nichtich** [thunken/beacon#5]
Woken up by your implementation I started to create a next (hopefully final) draft of BEACON specification. Have a look [at the current version](http://gbv.github.io/beaconspec/draft-voss-beacon-002.html). The major changes would be:

* Remove repeatability of some meta fields (do you know if any use case for this?)
* Add relation types via URI pattern in meta field RELATION
* Drop support of non-URI values in meta field RELATION

The first would simplify the code, the second would add a new method in `BeaconLink.java`, such as:

~~~java
public URI getRelationType() {
    String relation = metaFields.getValue(BeaconMetaField.RELATION);
    if (relation.contains('{+ID}') || relation.contains('{ID}') {
        return get(BeaconMetaField.RELATION, annotationToken);
    } else {
        return URI.create(relation)
    }
} 
~~~

I would like to know whether this change is compatible with your use case of BEACON

**Comment by lucboruta** [comment]
Glad to see that the spec isn't abandoned. :)

Regarding the changes you listed:
* Repeatability of some meta fields: I don't remember seeing repeated meta fields in the dumps we parse. The change would indeed simplify the code, and remove the dependency on Guava. We'd just need to deprecate the set-based getter for a while before actually removing it.
* Updated definition of RELATION: fully compatible with our use case.

I'll review the latest draft, but I think it'll work just fine for us.

**Comment by lucboruta** [comment]
What's the recommended behavior for repeated meta fields?

Should we silently overwrite any previous value with the last value we've parsed, ignore new values if we've already parsed one, or throw an exception?

**Comment by nichtich** [comment]
There is no rule, the parser can pick just one value (and possibly raise a warning). In any case repeatable fields are no syntax error so don't throw an exception.

The only use case for repeatable meta fields I have seen in practice is CREATOR given once as string and once as URL/URI. The application might prefer one over the other but just taking the first or the last one is also ok.

**Comment by lucboruta** [comment]
Thanks, I'll push a branch soon with the changes discussed in this ticket.

**Comment by lucboruta** [comment]
https://github.com/thunken/beacon/compare/feature/draft-voss-beacon-002 should now reflect the changes mentioned in the opening comment.

Before merging back to master, I'd like to add a couple methods to validate meta field values, e.g. to satisfy constraints like "The field value MUST be either an URI or a URI pattern." and issue proper warnings otherwise.

**Comment by lucboruta** [comment]
@nichtich, it took me a while to get back to this, but I think the implementation is now compliant with the latest draft.
